import { montserrat } from "./fonts";
import "./globals.scss";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Vocal Teacher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
